version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    environment:
      - PORT=3000
    depends_on: 
      - mongo

  mongo:
    image: mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=nrnlimbu"
      - "MONGO_INITDB_ROOT_PASSWORD=password"
      
  redis:
    image: redis
  
    
     